### PR TITLE
Css highlight

### PR DESCRIPTION
**Pull request by Novalis15**
trying out the rouge syntax highlighting css. The origin syntax highlighting is still available, you just have to change the `@import` statement in `style.sass`

### CODE REVIEW

**Comment by johannesvollmer** [comment]
Is this simply a different color scheme for the jekyll syntax hightlighting or am I missing something?

**Comment by johannesvollmer** [comment]
Also, Jekyll reports an error, but I can't find a problem in the source code. Do you know what happened there?

**Comment by johannesvollmer** [comment]
` Conversion error: Jekyll::Converters::Sass encountered an error while converting 'style.sass':
                    Error: Invalid CSS after "...und: #ffffff; }": expected 1 selector or at-rule, was "{" on line 4:25 of _sass/syntax-hightlighting-rouge.sass from line 1:1 of style.sass >> background: #ffffff; } { ------------------------^ `

**Comment by Novalis15** [comment]
yes, just a different color scheme.
The problem was based on tabs instead of spaces... i thought Sass could handle Tabs 😓 
Jekyll doesn't provide enough info for debugging in this case. Using sass manually solved the issue.
sass compile error

**Comment by Novalis15** [comment]
currently playing around with the color scheme.

**Comment by johannesvollmer** [comment]
Perfect, then just change to spaces and commit again when you're ready

**Comment by Novalis15** [comment]
branch is now ready to merge

**Comment by johannesvollmer** [comment]
why use scss instead of sass? those braces don't add that much of a value to the code, don't your think so?

**Pull request merged**
