### PR TITLE
improve structure

### PR DESCRIPTION
**Pull request by johannesvollmer**
- add 404
- use relative urls
- target blank on exernal urls
- reuse code

### CODE REVIEW

**Comment by johannesvollmer** [comment]
Well, that's a helpful message there

**Comment by johannesvollmer** [comment]
On my local machine, the gem `jekyll-target-blank` works just fine - however github pages seems to use a different version of that gem which has an error. Can we fix this or do we have to revert back to non-target-blank urls?

**Comment by johannesvollmer** [comment]
The other possibility is that our code contains a url which is technically not valid. I will scan the repository for suspicious urls, like redundant slashes or double colons

**Comment by johannesvollmer** [comment]
See this question for reference:
https://stackoverflow.com/questions/15700784/how-to-fix-bad-uri-is-not-uri

**Comment by Novalis15** [comment]
> On my local machine, the gem `jekyll-target-blank` works just fine - however github pages seems to use a different version of that gem which has an error. Can we fix this or do we have to revert back to non-target-blank urls?

Github Actions for building jekyll is also using `jekyll-target-blank 2.0.0`. Therefore it should actually work. Jekyll version is also 4.0.0.

**Comment by johannesvollmer** [comment]
Then it must be that one of the URLs is not correct. But why does it build on my machine then?

**Comment by Novalis15** [comment]
Did you use `bundle jekyll serve`? Because if i use `jekyll build` which is the build command in the github action, i get the same error as the CI pipeline.

**Comment by johannesvollmer** [comment]
Gonna test that

**Pull request merged**
